version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: blakkheart/foodgram_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - media:/app/media
      - static:/backend_static
  
  frontend:
    env_file:
      - .env
    image: blakkheart/foodgram_frontend
    command: cp -r /app/build/. /frontend/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: blakkheart/foodgram_gateway
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/