# Generated by Django 3.2.3 on 2023-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20231128_1057'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourites', through='recipe.RecipeFavourite', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_list',
            field=models.ManyToManyField(blank=True, related_name='shop_list', through='recipe.ReciepeShopList', to='recipe.Recipe'),
        ),
    ]
