# Generated by Django 3.2.3 on 2023-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shop_list',
        ),
    ]
