# Generated by Django 3.2.3 on 2023-12-11 12:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reciepeshoplist',
            managers=[
                ('ingredients', django.db.models.manager.Manager()),
            ],
        ),
    ]
