# Generated by Django 3.2.3 on 2023-12-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_reciepeshoplist_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reciepeshoplist',
            managers=[
            ],
        ),
    ]
